# Generated by Django 4.0 on 2022-05-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourse_link', models.URLField(max_length=550, verbose_name='Your link')),
                ('slug', models.SlugField(unique=True, verbose_name='Your url')),
            ],
        ),
    ]
