# Generated by Django 4.0 on 2022-05-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shortcuter', '0003_link_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.SlugField(verbose_name='Your slug'),
        ),
        migrations.AlterUniqueTogether(
            name='link',
            unique_together={('author', 'url')},
        ),
    ]
