# Generated by Django 4.0 on 2022-05-03 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortcuter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='slug',
            new_name='url',
        ),
    ]
