# Generated by Django 4.0 on 2022-05-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcuter', '0004_alter_link_url_alter_link_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='views'),
        ),
        migrations.AlterField(
            model_name='link',
            name='sourse_link',
            field=models.URLField(max_length=550, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.SlugField(verbose_name='slug'),
        ),
    ]
